### ISSUE TITLE
error: squares_text.o: No such file

### ISSUE THREAD

**Issue by Samrj12** [mvirgo/c-programming#1]
When I give input
gcc -o squares -Wall -Werror -std=gnu99 --pedantic squares.c squares_text.o

I get this error. Please help someone ASAP!!

**Comment by Samrj12** [comment]
![Capture](https://user-images.githubusercontent.com/67728483/86323888-468e5400-bc5b-11ea-9d2e-b92619e94f68.PNG)

**Comment by Shubhankita** [comment]
try this:
gcc squares -Wall -Werror -pedantic -std=gnu99 squares.c

**Comment by Samrj12** [comment]
Thank for you response!

I tried this as well. It displays this error:




![Capture #2](https://user-images.githubusercontent.com/67728483/86507947-af133780-bdf9-11ea-9474-b805b0ee2e0b.PNG)

**Comment by mvirgo** [comment]
Closing this since not related to the repo itself, looks like, and no further comments in ~six months.
